name: CI-Dev
on:
  push:
    branches: [ "dev" , "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: extract_version
        run: |
          echo "version=v0.`expr ${{ github.run_number }} / 10`.`expr ${{ github.run_number }} % 10`" >> $GITHUB_OUTPUT
      - name: Get Tags
        if: ${{ github.ref == 'main' }}
        id: tags
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          extracted_digit=$(echo "$latest_tag" | awk -F'[v.]' '{print $2}')
          echo "$extracted_digit"
          echo "version=v`expr $extracted_digit+1`.`expr ${{ github.run_number }} / 10`.`expr ${{ github.run_number }} % 10`" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
